### ISSUE TITLE
Do you plan to upgrade to the new Kube version?

### ISSUE THREAD

**Issue by kemar** [davidpelayo/kube#1]
Hi,

Thank you for bringing Kube to npm :)

There is a new version of Kube (that is unfortunately backward-incompatible).

Do you plan to upgrade the npm package? Or would you accept a pull request?
- https://imperavi.com/blog/introducing-new-kube/
- https://imperavi.com/kube/

Thanx

**Comment by davidpelayo** [comment]
Hi @kemar. 

Thanks for opening the issue. I've to review it carefully. 

But since this isn't so used by people nor even me, I think I won't have any issues on accepting a pull request to then republish the npm pagacke.

Please feel free to do it.

Thanks.
